//
// Created by test on 1/6/2022.
//

#ifndef LINKEDINLEARNINGCPPCOURSEWORK_TESTFOO_H
#define LINKEDINLEARNINGCPPCOURSEWORK_TESTFOO_H

#endif //LINKEDINLEARNINGCPPCOURSEWORK_TESTFOO_H

int foo(int x);
void bar(int y);